<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vikash-PC" name="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest" tests="5" failures="1" timestamp="29 Mar 2020 10:08:02 GMT" time="844.036" errors="0">
  <testcase name="validateSignInPage_PageHeading_SIP" time="85.837" classname="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateSignInPage_SignInSectionHeading_SIP" time="234.118" classname="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest">
    <failure type="java.lang.AssertionError" message="expected [ALREADY REGISTEREDD?] but found [ALREADY REGISTERED?]">
      <![CDATA[java.lang.AssertionError: expected [ALREADY REGISTEREDD?] but found [ALREADY REGISTERED?]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest.validateSignInPage_SignInSectionHeading_SIP(SignInTest.java:173)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- validateSignInPage_SignInSectionHeading_SIP -->
  <testcase name="validateSignInPageBreadcrumbText_SIP" time="169.536" classname="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateRegistrationSectionHeading_SignInPage_SIP" time="189.890" classname="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
  <testcase name="validateLoginProcess_SIP" time="164.655" classname="com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest"/>
</testsuite> <!-- com.a32hp.automationpracticee.framework.test.createaccountandlogin.SignInTest -->
